### ISSUE TITLE
Adding whisper instead of faster-whisper as stt

### ISSUE THREAD

**Issue by jevylux** [rhasspy/rhasspy3#61]
Hi, I would like to use whisper as stt module, as i want to try a specific model.
Couls someone explain me how to configure the configuration.yaml?
I install whisper,
and without any further modifications of configuration.yaml, when I try to run script/http_server --debug --server asr whisper --server tts piper

I get 
`DEBUG:rhasspy3.core:Loading config from /home/marc/rhasspy3/rhasspy3/configuration.yaml
DEBUG:rhasspy3.core:Loading config from /home/marc/rhasspy3/config/configuration.yaml
DEBUG:rhasspy:['server_run.py', '--config', '/home/marc/rhasspy3/config', 'asr', 'whisper']
INFO:rhasspy:Starting asr whisper
DEBUG:rhasspy:['server_run.py', '--config', '/home/marc/rhasspy3/config', 'tts', 'piper']
INFO:rhasspy:Starting tts piper
DEBUG:asyncio:Using selector: EpollSelector
[2024-01-18 11:51:05 +0100] [114103] [INFO] Running on http://0.0.0.0:13331 (CTRL + C to quit)
INFO:hypercorn.error:Running on http://0.0.0.0:13331 (CTRL + C to quit)
INFO:piper_server:Ready
Load time: 0.484693 sec
Output directory: "/tmp/tmpcbokrp99"
usage: whisper_server.py [-h] [--language LANGUAGE] [--device {cpu,cuda}] --socketfile SOCKETFILE [--debug] model
whisper_server.py: error: unrecognized arguments: --model-directory tiny.en
ERROR:rhasspy:Unexpected error running server: domain=asr, name=whisper
Traceback (most recent call last):
  File "/home/marc/rhasspy3/rhasspy3_http_api/__main__.py", line 159, in run_server
    subprocess.run(command, check=True, cwd=rhasspy.base_dir, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['server_run.py', '--config', '/home/marc/rhasspy3/config', 'asr', 'whisper']' returned non-zero exit status 2.`

**Comment by Shulyaka** [comment]
Check my PR: https://github.com/rhasspy/rhasspy3/pull/41
